[package]
name = "leveldb-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
crc32fast = "1.4.2"
futures = "0.3.31"
rand="0.8"
snappy = "0.4.0"
tokio = { version = "1.37", features = ["full"] }
zstd = "0.13.3"
